# Generated by Django 4.2.7 on 2026-07-16 23:17

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('produits', '0001_initial'),
        ('membres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveSmallIntegerField(default=1)),
                ('montant_total', models.PositiveIntegerField()),
                ('acompte_requis', models.PositiveIntegerField()),
                ('montant_verse', models.PositiveIntegerField(default=0)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('acompte_paye', 'Acompte payé'), ('soldee', 'Soldée'), ('annulee', 'Annulée'), ('en_retard', 'En retard')], default='en_attente', max_length=15)),
                ('date_commande', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_limite_solde', models.DateField(blank=True, null=True)),
                ('penalite_activee', models.BooleanField(default=True, help_text='Décochez pour suspendre les pénalités sur cette commande.', verbose_name='Pénalités activées')),
                ('penalite_taux', models.DecimalField(decimal_places=4, default=Decimal('0.0100'), help_text='Ex: 0.01 = 1% par jour. Modifiable par commande.', max_digits=5, verbose_name='Taux pénalité/jour')),
                ('penalite_totale', models.PositiveIntegerField(default=0, verbose_name='Pénalités cumulées (FCFA)')),
                ('penalite_remisee', models.PositiveIntegerField(default=0, help_text="Montant de pénalités effacé manuellement par l'admin.", verbose_name='Remise accordée sur pénalités (FCFA)')),
                ('penalite_note_admin', models.TextField(blank=True, help_text="Raison d'une remise ou modification de pénalité.", verbose_name='Note admin (pénalités)')),
                ('commission_calculee', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True)),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes', to='membres.membre')),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes', to='produits.pack')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['-date_commande'],
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.PositiveIntegerField()),
                ('date_paiement', models.DateTimeField(default=django.utils.timezone.now)),
                ('mode_paiement', models.CharField(choices=[('especes', 'Espèces'), ('mobile_money', 'Mobile Money (Flooz/TMoney)'), ('virement', 'Virement bancaire')], default='especes', max_length=15)),
                ('note', models.TextField(blank=True)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='commandes.commande')),
                ('enregistre_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_enregistres', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-date_paiement'],
            },
        ),
    ]
