# Generated by Django 4.2.30 on 2026-06-19 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('membres', '0001_initial'),
        ('produits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveSmallIntegerField(default=1)),
                ('montant_total', models.PositiveIntegerField(verbose_name='Montant total (FCFA)')),
                ('acompte_requis', models.PositiveIntegerField(verbose_name='Acompte requis (FCFA)')),
                ('montant_verse', models.PositiveIntegerField(default=0, verbose_name='Montant versé (FCFA)')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('acompte_paye', 'Acompte payé'), ('soldee', 'Soldée'), ('annulee', 'Annulée'), ('en_retard', 'En retard')], default='en_attente', max_length=15)),
                ('date_commande', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_limite_solde', models.DateField(blank=True, null=True, verbose_name='Date limite règlement')),
                ('penalite_totale', models.PositiveIntegerField(default=0, verbose_name='Pénalités cumulées (FCFA)')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('commission_calculee', models.BooleanField(default=False)),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes', to='membres.membre', verbose_name='Membre')),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes', to='produits.pack', verbose_name='Pack')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['-date_commande'],
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.PositiveIntegerField(verbose_name='Montant (FCFA)')),
                ('date_paiement', models.DateTimeField(default=django.utils.timezone.now)),
                ('mode_paiement', models.CharField(choices=[('especes', 'Espèces'), ('mobile_money', 'Mobile Money (Flooz/TMoney)'), ('virement', 'Virement')], default='especes', max_length=15)),
                ('note', models.TextField(blank=True)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='commandes.commande')),
                ('enregistre_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_enregistres', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-date_paiement'],
            },
        ),
    ]
