# Generated by Django 6.0.6 on 2026-07-15 20:50

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0001_initial'),
        ('membres', '0001_initial'),
        ('produits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='penalite_activee',
            field=models.BooleanField(default=True, help_text='Décochez pour suspendre les pénalités sur cette commande.', verbose_name='Pénalités activées'),
        ),
        migrations.AddField(
            model_name='commande',
            name='penalite_note_admin',
            field=models.TextField(blank=True, help_text="Raison d'une remise ou modification de pénalité.", verbose_name='Note admin (pénalités)'),
        ),
        migrations.AddField(
            model_name='commande',
            name='penalite_remisee',
            field=models.PositiveIntegerField(default=0, help_text="Montant de pénalités effacé manuellement par l'admin.", verbose_name='Remise accordée sur pénalités (FCFA)'),
        ),
        migrations.AddField(
            model_name='commande',
            name='penalite_taux',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0100'), help_text='Ex: 0.01 = 1% par jour. Modifiable par commande.', max_digits=5, verbose_name='Taux pénalité/jour'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='acompte_requis',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='commande',
            name='date_limite_solde',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='membre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes', to='membres.membre'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='montant_total',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='commande',
            name='montant_verse',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='commande',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='pack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes', to='produits.pack'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='mode_paiement',
            field=models.CharField(choices=[('especes', 'Espèces'), ('mobile_money', 'Mobile Money (Flooz/TMoney)'), ('virement', 'Virement bancaire')], default='especes', max_length=15),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='montant',
            field=models.PositiveIntegerField(),
        ),
    ]
