# Generated by Django 6.1 on 2026-08-08 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0002_commande_penalite_activee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='mode_commande',
            field=models.CharField(choices=[('credit', 'À crédit (acompte 50%)'), ('cash', 'Comptant (paiement total)')], default='credit', max_length=10, verbose_name='Mode de paiement'),
        ),
    ]
