# Generated by Django 4.2.7 on 2026-07-16 23:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import membres.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(max_length=20)),
                ('adresse', models.CharField(max_length=200)),
                ('zone', models.CharField(default='Lomé', max_length=100)),
                ('personne_confiance_nom', models.CharField(max_length=100)),
                ('personne_confiance_tel', models.CharField(max_length=20)),
                ('code_parrainage', models.CharField(default=membres.models.generer_code_parrainage, max_length=10, unique=True)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('suspendu', 'Suspendu')], default='actif', max_length=10)),
                ('contrat_accepte', models.BooleanField(default=False)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('photo_profil', models.ImageField(blank=True, null=True, upload_to='kyc/photos/', verbose_name='Photo de profil')),
                ('carte_identite_recto', models.ImageField(blank=True, null=True, upload_to='kyc/cni/', verbose_name='CNI Recto')),
                ('carte_identite_verso', models.ImageField(blank=True, null=True, upload_to='kyc/cni/', verbose_name='CNI Verso (optionnel)')),
                ('kyc_statut', models.CharField(choices=[('en_attente', 'En attente de vérification'), ('valide', 'Vérifié ✅'), ('rejete', 'Rejeté ❌')], default='en_attente', max_length=12, verbose_name='Statut KYC')),
                ('kyc_note', models.TextField(blank=True, verbose_name='Note KYC admin')),
                ('score_confiance', models.PositiveSmallIntegerField(default=30, verbose_name='Score de confiance (/100)')),
                ('note_admin', models.TextField(blank=True)),
                ('parrain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filleuls', to='membres.membre')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='membre', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Membre',
                'verbose_name_plural': 'Membres',
                'ordering': ['-date_inscription'],
            },
        ),
    ]
