# Generated by Django 6.1 on 2026-08-08 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membres', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membre',
            name='kyc_statut',
            field=models.CharField(choices=[('non_requis', 'Non requis encore'), ('en_attente', 'En attente de vérification'), ('valide', 'Vérifié ✅'), ('rejete', 'Rejeté ❌')], default='non_requis', max_length=12, verbose_name='Statut KYC'),
        ),
    ]
