# Generated by Django 6.1 on 2026-08-08 10:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriePartenaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=80)),
                ('slug', models.SlugField(unique=True)),
                ('emoji', models.CharField(default='🏢', max_length=5)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Catégorie partenaire',
                'verbose_name_plural': 'Catégories partenaires',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Partenaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120)),
                ('slogan', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partenaires/logos/')),
                ('image_couverture', models.ImageField(blank=True, null=True, upload_to='partenaires/covers/')),
                ('telephone', models.CharField(max_length=25)),
                ('whatsapp', models.CharField(blank=True, max_length=25)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('site_web', models.URLField(blank=True)),
                ('zone', models.CharField(default='Lomé', max_length=100)),
                ('adresse', models.CharField(blank=True, max_length=200)),
                ('statut', models.CharField(choices=[('actif', 'Actif ✅'), ('inactif', 'Inactif'), ('en_attente', 'En attente de validation')], default='en_attente', max_length=12)),
                ('plan', models.CharField(choices=[('starter', 'Starter — 5 000 FCFA/mois'), ('standard', 'Standard — 10 000 FCFA/mois'), ('premium', 'Premium — 20 000 FCFA/mois')], default='starter', max_length=12)),
                ('date_debut', models.DateField(default=django.utils.timezone.now)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('note_admin', models.TextField(blank=True)),
                ('ordre_affichage', models.PositiveSmallIntegerField(default=0)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partenaires', to='partenaires.categoriepartenaire')),
            ],
            options={
                'verbose_name': 'Partenaire',
                'verbose_name_plural': 'Partenaires',
                'ordering': ['ordre_affichage', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='ProduitPartenaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('prix', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='partenaires/produits/')),
                ('disponible', models.BooleanField(default=True)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('partenaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='partenaires.partenaire')),
            ],
            options={
                'verbose_name': 'Produit partenaire',
                'verbose_name_plural': 'Produits partenaires',
                'ordering': ['ordre', 'nom'],
            },
        ),
    ]
