# Generated by Django 4.2.7 on 2026-07-16 23:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commandes', '0001_initial'),
        ('membres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taux', models.DecimalField(decimal_places=4, max_digits=5, verbose_name='Taux')),
                ('montant', models.PositiveIntegerField(verbose_name='Montant (FCFA)')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de versement'), ('versee', 'Versée')], default='en_attente', max_length=12)),
                ('date_calcul', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_versement', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='commission', to='commandes.commande', verbose_name='Commande source')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commissions', to='membres.membre', verbose_name='Bénéficiaire')),
            ],
            options={
                'verbose_name': 'Commission',
                'verbose_name_plural': 'Commissions',
                'ordering': ['-date_calcul'],
            },
        ),
    ]
