# Generated by Django 4.2.7 on 2026-07-16 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('1A', 'Pack 1A'), ('2A', 'Pack 2A'), ('2B', 'Pack 2B'), ('3A', 'Pack 3A'), ('3B', 'Pack 3B'), ('4A', 'Pack 4A'), ('4B', 'Pack 4B')], max_length=5, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prix', models.PositiveIntegerField(help_text='Prix en FCFA')),
                ('description', models.TextField(blank=True)),
                ('note_quantite', models.CharField(blank=True, help_text='Ex: "EN QUANTITÉ PLUS ÉLEVÉE" ou "GRANDE QUANTITÉ"', max_length=100)),
                ('couleur', models.CharField(choices=[('blue', 'Bleu'), ('green', 'Vert'), ('orange', 'Orange'), ('navy', 'Marine'), ('purple', 'Violet'), ('red', 'Rouge'), ('darkgreen', 'Vert foncé')], default='blue', max_length=15)),
                ('disponible', models.BooleanField(default=True)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Pack',
                'verbose_name_plural': 'Packs',
                'ordering': ['ordre', 'prix'],
            },
        ),
        migrations.CreateModel(
            name='Composant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Ex: Riz, Huile végétale (1L), Milo', max_length=100)),
                ('emoji', models.CharField(blank=True, help_text='Emoji représentatif', max_length=5)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='composants', to='produits.pack')),
            ],
            options={
                'verbose_name': 'Composant',
                'verbose_name_plural': 'Composants',
                'ordering': ['ordre'],
            },
        ),
    ]
